headers:

  required:

    - { name: 'Content-Security-Policy', values: [] }
    - { name: 'X-Frame-Options', values: ['sameorigin', 'deny'] }
    - { name: 'X-XSS-Protection', values: ['1; mode=block'] }
    - { name: 'X-Content-Type-Options', values: ['nosniff'] }

  removed:

    - { name: 'ETag' }
    - { name: 'X-Powered-By' }
    - { name: 'X-Powered-By-Plesk' }
    - { name: 'Server' }
    - { name: 'Via' }

content:

  # Generator
  - { name: 'Generator name', selector: '/html/head/meta[@name="generator"]/@content' }
  - { name: 'Generator name', selector: '/html/head/meta[@name="author"]/@content' }
  - { name: 'Generator name', selector: '/html/head/meta[@name="DC.creator"]/@content' }

  # Email
  -
    name: 'Email'
    regex: mailto:([^"'\s>]+)
    selector: '/html/head/meta[@name="reply-to"]/@content'

  # Phone
  -
    name: 'Phone'
    regex: (?:callto|tel):([^"'>]+)

  # Skype
  -
    name: 'Skype'
    regex: skype:([^"'\s>]+)

  # Bitly
  - { name: 'Bitly application ID', selector: '/html/head/meta[@name="bitly-verification"]/@content' }

  # Twitter
  - { name: 'Twitter application ID', selector: '/html/head/meta[@name="twitter:site"]/@content' }
  - { name: 'Twitter creator ID', selector: '/html/head/meta[@name="twitter:creator"]/@content' }
  - { name: 'Apple application ID', selector: '/html/head/meta[@name="twitter:app:id:iphone"]/@content' }
  - { name: 'GooglePlay application ID', selector: '/html/head/meta[@name="twitter:app:id:googleplay"]/@content' }

  # Facebook
  - { name: 'Facebook admins ID', selector: '/html/head/meta[@property="fb:admins"]/@content' }
  - { name: 'Facebook application ID', selector: '/html/head/meta[@property="fb:app_id"]/@content' }

  # Google
  - { name: 'Google webmaster tools ID', selector: '/html/head/meta[@name="google-site-verification"]/@content' }
  -
    name: 'Google analytics ID'
    selector: '/html/head/meta[@name="google-analytics"]/@content'
    regex:
      - _gaq\s*\.\s*push\s*\(\s*\[\s*['"]_setAccount['"]\s*,\s*['"](.+?)['"]
      - ga\s*\(\s*['"]create['"]\s*,\s*['"](.+?)['"]

  # quantcast.com
  -
    name: 'quantcast.com'
    regex: _qevents\s*\.\s*push\s*\(\s*\{\s*qacct\s*:\s*['"](.+?)['"]

  # scorecardresearch.com
  -
    name: 'scorecardresearch.com'
    regex: _comscore\s*\.\s*push\s*\(\s*\{\s*c1\s*:\s*['"].+?['"]\s*,\s*c2\s*:\s*['"](.+?)['"]

  # estat.com
  -
    name: 'estat.com'
    regex:
      - eStat_id\s*\.\s*(serial)\s*\(\s*['"](.+?)['"]
      - eStat_id\s*\.\s*(master)\s*\(\s*['"](.+?)['"]

admin:

    # Wordpress
    - { path: ['/wp-login.php'] }

    # Spip
    - { path: ['/spip.php?page=login'] }

    # Joomla
    - { path: ['/administrator/'] }

    # Prestashop
    - { path: ['/admin-dev/'] }

    # Symfony
    - { path: ['/app_dev.php/'] }

    # Common
    - { path: ['/admin/', '/admin.php', '/manager/'] }

files:

  required:

    # Robots
    - 'robots.txt'

  removed:

    # Default
    - { files: ['/LICENSE', '/LICENSE.md', '/license.txt'] }
    - { files: ['/README', '/README.md', '/readme.html'] }

    # Settings
    - { files: ['/parameters.yml', '/settings.yml', '/config.yml'] }

    # Git
    - { files: ['/.gitignore'] }

    # Docker
    - { files: ['/docker-compose.yml'] }

    # Npm
    - { files: ['/package.json'] }

    # Bower
    - { files: ['/bower.json'] }

    # Composer
    - { files: ['/composer.json'], interpreter: { type: json, path: [require], category: php } }
    - { files: ['/composer.lock'] }
    - { files: ['/vendor/composer/installed.json'], interpreter: { type: json, path: [name, version], category: php } }

    # BrunchJs
    - { files: ['/brunch-config.js'] }

    # PhpUnit
    - { files: ['/phpunit.xml'] }
