headers:

    required:
        content_security_policy:
            name: 'Content-Security-Policy'
            values:
        x_frame_options:
            name: 'X-Frame-Options'
            values:
                - 'SAMEORIGIN'
                - 'DENY'
        x_xss_protection:
            name: 'X-XSS-Protection'
            values:
                - '1; mode=block'
    removed:
        etag:
            name: 'ETag'
        x_powered_by:
            name: 'X-Powered-By'

content:
    generatorName':
        name: 'Generator name'
        selector: '/html/head/meta[@name="generator"]/@content'
    bitlyAppId:
        name: 'Bitly application Id'
        selector: '/html/head/meta[@name="bitly-verification"]/@content'
    twitterAppId:
        name: 'Twitter application Id'
        selector: '/html/head/meta[@name="twitter:site"]/@content'
    facebookAppId:
        name: 'Facebook application Id'
        selector: '/html/head/meta[@property="fb:admins"]/@content'
    iphoneAppId:
        name: 'iPhone application Id'
        selector: '/html/head/meta[@name="twitter:app:id:iphone"]/@content'

files:
    required:
        - 'robots.txt'

    removed:

        - '.gitignore'

        - 'LICENSE'
        - 'LICENSE.md'
        - 'README.md'

        - 'docker-compose.yml'
        - 'parameters.yml'
        - 'settings.yml'
        - 'config.yml'

        - 'package.json'
        - 'bower.json'
        - 'composer.json'
        - 'composer.lock'

        - 'brunch-config.js'

        - 'phpunit.xml'
